### PR TITLE
Suppress severe warnings

### PR DESCRIPTION
**Pull request by shenki**
These warnings are reported as severe by ISE 14.7, however none of them appear to be real issues - in all cases the HDL compiler is assuming that adding `1` to a signal will cause it to overflow. This may or not be true. For some reason, the compiler can be silenced by instead adding `1b1`, ie a signal 1  that is of length 1.

I have checked that there is no real error being reported by the warnings, so I believe it is safe to suppress them.

### CODE REVIEW

**Comment by ajitmathew** [comment]
Every thing looks good.

**Comment by shenki** [comment]
It appears the number of warnings goes up a lot after these fixes.

Need to investigate if they're warnings that were hiding behind the severe warnings, of if my fixes have introduced new problems.

**Comment by mithro** [comment]
Poke?

**Comment by shenki** [comment]
You decided to close it?

**Comment by mithro** [comment]
Feel free to reopen when "Need to investigate if they're warnings that were
hiding behind the severe warnings, of if my fixes have introduced new
problems."

Tim

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!

**Pull request closed without merging**
