### PR TITLE
DCT1 register initial vs. register reset values.

### PR DESCRIPTION
**Pull request by cfelton**
These changes are part of the "minimize" synthesis warnings effort.  Note: this PR might be hosed, looks like I might have fallen into a common git pitfall.  I might need to recreate this and figure out some cryptic git commands ...

### CODE REVIEW

**Comment by shenki** [comment]
Hi @cfelton, looks great! I have taken a clone of your changes and made the following fixes
- resolved your git issue. Not sure what happened there. The way I fixed it was to rebase your branch on top of timvideos master:

```
  git clone https://github.com/timvideos/HDMI2USB
  git remote add cfelton https://github.com/cfelton/HDMI2USB
  git fetch cfelton
  git checkout -b cfelton-master cfelton/master
  git rebase origin/master
```
- Removed the whitespace changes. Our codebase is a mess, and I have a pending branch that reformats it using emacs. For now, I re-created your patches ignoring any whitepace change
- Fixed the author information. Your name is currently set to cfelton. Fix it by doing this:

```
   git config --global user.name "Chris Felton"
```

It would be good to beef up the commit messages a bit, explaining what you're doing and why, so that others can learn from your changes. For instance, the removal of std_logic_arith could look like this, except with more factually accurate content. If you're fixing warnings, then some text that shows the warning would be informative.

```
jpeg_encoder: Remove std_logic_arith

The module IEEE.STD_LOGIC_UNSIGNED is evil, as it causes bugs and makes baby Simba sad. Instead use IEEE.numeric_std, as this is best practice, as it makes your unicorns fart rainbows.

This resolves the following warnings:

The FF/Latch <U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_full_i> in Unit <selector_fifo> is equivalent to the following FF/Latch : <U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_full_fb_i>
```

Please take a clone of my shenki/cfelton-fixes@0eda9201267349facaa5a65b01dca14facf3b48a branch, make any changes you wish to make, and re-submit the pull request.

**Comment by cfelton** [comment]
The link at the end did **not** work to the patched up branch.  I am unable to clone it.

Thanks for taking the time to cleanup the PR.  Majority of the whitespace changes were made mainly to ease editing, block editing / column editing, same change for many lines.

**Comment by shenki** [comment]
Sorry, not sure what I did wrong there. Try this link:

 https://github.com/shenki/HDMI2USB/commits/cfelton-fixes

**Comment by mithro** [comment]
Friendly ping! I assume you have just been busy - anything you need from us to help get this merged in? Would it be helpful to get Joel to submit a pull request from his fixed up?

Thanks for your help!

**Comment by cfelton** [comment]
Yes, probably have Joel submit I have been flailing around with git.  I have not been able to get a pull request to look correct, no clue why.  Followed the directions above, when I performed the task on my repo nothing seemed to changed (no freebasing), when pulling from shenki couldn't get it pushed to my repo (excuses, excuses).

I updated the [commit comment](https://github.com/cfelton/HDMI2USB/commit/6d64958ea7eed98e0de73fddc1b38ab2f8d9464a) but as mentioned it still has all the previous changes (rebase didn't occur????).

**Comment by mithro** [comment]
I'm happy to walk you through the git stuff on IRC if you would like to get
to the bottom of it.

**Comment by cfelton** [comment]
@mithro Thanks, I only have IRC access at odd times and not consistent.  If I happen to be on IRC at some point, I will gladly take a walk through.  I should bite my tongue but these issues don't happen with hg - it just works (no freebasing).  I should stick to scopes and specAs :)

**Comment by mithro** [comment]
Merged @shenki 's pull request as requested. Closing this request.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!

**Pull request closed without merging**
